### ISSUE TITLE
ImportError when trying to import get_samples from medhalt.prompts

### ISSUE THREAD

**Issue by tathagata-raha** [medhalt/medhalt#1]
When I attempt to run `model.py`, I encounter an ImportError related to the `get_samples` function. Specifically, I see the following error message:

```
ImportError: cannot import name 'get_samples' from 'medhalt.prompts'
```

**Steps to reproduce:**
1. Execute `model.py`.
2. Observe the ImportError.

**Expected Behavior:**
`model.py` should be able to successfully import the `get_samples` function from the `medhalt.prompts` module.

**Actual Behavior:**
Received an ImportError indicating that `get_samples` cannot be imported from `medhalt.prompts`.

**Additional Information:**
- It seems that there might be an issue either with the location of the `get_samples` function or with the way `utils.py` is trying to import it.
- I've verified that `get_samples` does not exists in the `prompts` folder.

---

**Comment by infinitylogesh** [comment]
Hi @tathagata-raha , Thank you for bringing this to our notice and detailed explanation of the issue. Seems like a few files have been missed in our public commit. We are working to fix this.

**Comment by infinitylogesh** [comment]
@tathagata-raha  Can you please check if you still face the issue after the fix ? Thanks in advance.
